### ISSUE TITLE
Definir tecnologías para front-end

### ISSUE THREAD

**Issue by hrnn** [Bits-nFingers/Bits-nFingers#10]
Historia de Usuario
**COMO:** Grupo
**QUEREMOS:** Definir las tecnologias que usaremos para front-end
**PARA QUE:** Para poder implementarla

**Comment by jurgenru** [comment]
Viendo si vamos a usar HTML o JavaScript

**Comment by jurgenru** [comment]
Vamos a usar Android Studio dado por que la mayoría sabe usar esa herramienta

**Comment by jurgenru** [comment]
Historia de Usuario
<b>COMO:</b> Grupo
<b>QUEREMOS:</b> Definir las tecnologias que usaremos para front-end  
<b>PARA QUE:</b> Para poder implementarla
