### ISSUE TITLE
Definir tecnologías para back-end

### ISSUE THREAD

**Issue by hrnn** [Bits-nFingers/Bits-nFingers#11]
Historia de Usuario
**COMO:** Grupo
**QUEREMOS:** Lograr toda la documentacion
**PARA QUE:** Pueda realizar varias acciones como añadir contenidos nuevos

**Comment by SergiusxD** [comment]
Con el Grupo vamos usar Java (Android Studie), puesto que es lo que la  mayoria sabe

**Comment by SergiusxD** [comment]
Por ser Java vamos a usar Android estudio junto con mongoBD
https://docs.google.com/document/d/15_llkuhP-5snPXXtlnwob0NrWarV9gh5_WMhzeXin8s/edit?usp=sharing

**Comment by jurgenru** [comment]
Historia de Usuario
<b>COMO:</b> Grupo
<b>QUEREMOS:</b> Lograr toda la documentacion  
<b>PARA QUE:</b> Pueda realizar varias acciones como añadir contenidos nuevos
