### ISSUE TITLE
Definir si el proyecto sera monorepo o multirepo

### ISSUE THREAD

**Issue by hrnn** [Bits-nFingers/Bits-nFingers#12]
Historia de Usuario
<b>COMO:</b> Grupo
<b>QUEREMOS:</b> Definir si el proyecto sera monorepo o multirepo
<b>PARA QUE:</b> Podamos ver si el proyecto lo vamos a dividir en un repositorio o en varios

**Comment by jurgenru** [comment]
Estamos decidiendo cual usar si queremos separar o no el código en diferentes repositorios

**Comment by jurgenru** [comment]
Historia de Usuario
<b>COMO:</b> Grupo
<b>QUEREMOS:</b> Definir si el proyecto sera monorepo o multirepo  
<b>PARA QUE:</b> Para que podamos ver si el proyecto lo vamos a dividir en un repositorio o en varios
