### ISSUE TITLE
Definir si se usará git flow

### ISSUE THREAD

**Issue by hrnn** [Bits-nFingers/Bits-nFingers#13]
Historia de Usuario
<b>COMO:</b> Grupo
<b>QUEREMOS:</b> Definir si se usara git flow
<b>PARA QUE:</b> Veamos si nos facilita en el desarrollo de la aplicación

**Comment by jurgenru** [comment]
El profe dijo que nos iba a enseñar a usar esto

**Comment by jurgenru** [comment]
Historia de Usuario
<b>COMO:</b> Grupo
<b>QUEREMOS:</b> Definir si se usara git flow  
<b>PARA QUE:</b> Para ver si nos facilita en el desarrollo de la aplicación

**Comment by jurgenru** [comment]
vamos a usar git flow? @SergiusxD @PaoRivas @AndreaAguilar26

**Comment by SergiusxD** [comment]
No, ya no vamos a usar
