### ISSUE TITLE
Diseñar diagrama de Casos de Uso

### ISSUE THREAD

**Issue by PaoRivas** [Bits-nFingers/Bits-nFingers#16]
Historia de Usuario
<b>COMO:</b> Grupo
<b>QUEREMOS:</b> Diseñar diagrama de Casos de Uso
<b>PARA QUE:</b> Veamos cómo va a ser la comunicación del sistema

**Comment by PaoRivas** [comment]
Al tener un primer diseño de los mockups, comenzamos a realizar los casos de uso.

**Comment by jurgenru** [comment]
Historia de Usuario
<b>COMO:</b> Grupo
<b>QUEREMOS:</b> Diseñar los diagramas de uso 
<b>PARA QUE:</b> Para que podamos definir las interacciones de cada actor
