### ISSUE TITLE
El diagrama de la Base de datos

### ISSUE THREAD

**Issue by SergiusxD** [Bits-nFingers/Bits-nFingers#19]
Historia de Usuario
<b>COMO:</b> Grupo
<b>QUEREMOS:</b> Crear el diagrama de base de datos relacional
<b>PARA QUE:</b> Entendamos cómo  interactuará con el software

**Comment by SergiusxD** [comment]
Aun falta terminarlo este es un ejemplo que vamos a tratar de seguir
https://docs.google.com/document/d/19N_KZ9NQWBA1syda8diAQzZCqlKJAh_38T9nTfpgs4k/edit?usp=sharingo

**Comment by AndreaAguilar26** [comment]
se realizo en el software ""DIA"

**Comment by AndreaAguilar26** [comment]
![diagrama de base de datos](https://user-images.githubusercontent.com/57947101/70488337-bde97400-1ace-11ea-9434-e5e90fc0b597.jpg)

**Comment by AndreaAguilar26** [comment]
@SergiusxD la primera parte de la base esta mal!

**Comment by PaoRivas** [comment]
Me parece que esta demás la clase usuario, la clase registro debería ser la clase usuario y tener el parámetro cargo.

**Comment by SergiusxD** [comment]
ya pues, pues entonces cambienlo si dicen que esta mal, ni modales

**Comment by SergiusxD** [comment]
@AndreaAguilar26 editalo lo del usuario ponlo en lo de registro y eliminas el usuario plx

**Comment by PaoRivas** [comment]
@AndreaAguilar26 diferencia los códigos con "códigoEmpleado" y "códigoMaterial", "nombreUsuario" y "nombreMaterial" en todas las clases, tienen que seguir un solo sentido.
"cantidadMaterial" y "cantidadAPedir" está bien diferenciado.

**Comment by AndreaAguilar26** [comment]
![base de datos new](https://user-images.githubusercontent.com/57947101/70819390-7f90d500-1dac-11ea-8cdc-4992db93f5a8.jpg)

**Comment by AndreaAguilar26** [comment]
@SergiusxD ya esta!!!!!!!!!!!!!!!!!

**Comment by SergiusxD** [comment]
LIsto ahora si esta bien
