### ISSUE TITLE
Empezar a codear el Proyecto

### ISSUE THREAD

**Issue by SergiusxD** [Bits-nFingers/Bits-nFingers#21]
Historia de Usuario
<b>COMO:</b> Grupo
<b>QUEREMOS:</b> Empezar el proyecto
<b>PARA QUE:</b> Presentemos un proyecto funcional y con todas las especificaciones que se pidió

**Comment by SergiusxD** [comment]
Empeze un poco para poder mostrar un poco como sera nuestra aplicacion

**Comment by jurgenru** [comment]
ya tengo los servicios rest ya los subi a el otro repository

**Comment by SergiusxD** [comment]
Ahora empezas
