### ISSUE TITLE
Servicios rest 

### ISSUE THREAD

**Issue by jurgenru** [Bits-nFingers/Bits-nFingers#22]
Historia de Usuario
<b>COMO:</b> Grupo
<b>QUEREMOS:</b> Utilizar servicios rest 
<b>PARA QUE:</b > Para poder usar la aplicación de manera eficiente y que se conecte correctamente con la base de datos

**Comment by jurgenru** [comment]
ver que es y como usar los servicios rest

**Comment by AndreaAguilar26** [comment]
@jurgenru no te olvides arreglar la primera parte !!!!!!!!!!!!!!!!!!!

**Comment by SergiusxD** [comment]
y nos tienes que enseñar loque hiciste

**Comment by jurgenru** [comment]
yaya lo arreglare @SergiusxD  @AndreaAguilar26  @PaoRivas  ya les enseñare hoy muchachos

**Comment by jurgenru** [comment]
ya se logro crear los apis para la base de datos

**Comment by jurgenru** [comment]
estamos averiguando swagger

**Comment by AndreaAguilar26** [comment]
![diseño del servidor Rest](https://user-images.githubusercontent.com/57947101/70843059-500cb780-1e02-11ea-8421-da8ccb49fc6a.jpg)
