### ISSUE TITLE
Manejo De Proyecto

### ISSUE THREAD

**Issue by jurgenru** [Bits-nFingers/Bits-nFingers#25]

**Comment by jurgenru** [comment]
que era esto? @SergiusxD @AndreaAguilar26 @PaoRivas

**Comment by SergiusxD** [comment]
![Screenshot_2019-12-01-22-02-09-265_com google android apps docs](https://user-images.githubusercontent.com/25600687/70621639-70fdbe80-1bf0-11ea-864d-ee05f2ab8746.jpg)
Esto es pues @jurgenru

**Comment by jurgenru** [comment]
Gracias creo que ya tenemos la mayoría pero tenemos que seguir revisando

**Comment by AndreaAguilar26** [comment]
Historia de Usuario
<b>COMO:</b> Grupo
<b>QUEREMOS:</b> manejo del proyecto
<b>PARA QUE:</b> Para especificar la comunicación y el comportamiento de el sistema
