### ISSUE TITLE
Diseñar el diagrama Orientado a Objetos

### ISSUE THREAD

**Issue by PaoRivas** [Bits-nFingers/Bits-nFingers#26]

**Comment by PaoRivas** [comment]
![clases](https://user-images.githubusercontent.com/43442792/70620459-bcfb3400-1bed-11ea-9f49-cf8b6747f8a5.png)

aquí está el diagrama prros :)

**Comment by SergiusxD** [comment]
yaya esta bieen, pero comportate en tus comentarios

**Comment by jurgenru** [comment]
que c

**Comment by jurgenru** [comment]
que tipo de diagrama es el prros? @PaoRivas

**Comment by PaoRivas** [comment]
![clases_1](https://user-images.githubusercontent.com/43442792/70621520-2ed47d00-1bf0-11ea-8a34-bb3f6c18ae99.png)

Aquí está mejorado Amixes

**Comment by AndreaAguilar26** [comment]
Historia de Usuario
<b>COMO:</b> Grupo
<b>QUEREMOS:</b> Diseñar los diagrama orientado a objetos
<b>PARA QUE:</b> Para ver el funcionamiento del sistema y sus relaciones
