### ISSUE TITLE
Diseñar el diagrama de secuencia

### ISSUE THREAD

**Issue by PaoRivas** [Bits-nFingers/Bits-nFingers#27]

**Comment by PaoRivas** [comment]
![secuencia1](https://user-images.githubusercontent.com/43442792/70404372-2f162200-1a10-11ea-84d4-052e3f8dc4ca.png)

![secuencia2](https://user-images.githubusercontent.com/43442792/70404382-363d3000-1a10-11ea-8afa-936f1e679e13.png)

![secuencia3](https://user-images.githubusercontent.com/43442792/70404386-3c331100-1a10-11ea-915c-82e68fb8de7d.png)

**Comment by AndreaAguilar26** [comment]
@PaoRivas creo q se debe aumentar la introducción en los diagramas de secuencia

**Comment by PaoRivas** [comment]
@AndreaAguilar26  no entiendo... como la intro? Una descripción de cada diagrama?

**Comment by SergiusxD** [comment]
Historia de Usuario
**COMO**: Grupo
**QUEREMOS**: Tendemos un diaagrama de Secuencias
**PARA QUE**: Para ubicar que hace nuesto servis Rest
