### ISSUE TITLE
Creando los layout segun nuestros MockUps

### ISSUE THREAD

**Issue by SergiusxD** [Bits-nFingers/Bits-nFingers#29]

**Comment by SergiusxD** [comment]
creando solo vista

**Comment by SergiusxD** [comment]
Ya estan todos los Layouts, ya pueden actualizar para que tengan  @AndreaAguilar26 @jurgenru @PaoRivas

**Comment by AndreaAguilar26** [comment]
Historia de Usuario
<b>COMO:</b> Grupo
<b>QUEREMOS:</b> crear los layouts según nuestros mockups
<b>PARA QUE:</b> Para poder saber como se manejara el programa
