### ISSUE TITLE
Ir creando wiki para guiarnos

### ISSUE THREAD

**Issue by jurgenru** [Bits-nFingers/Bits-nFingers#3]
Historia de Usuario
**COMO:** Grupo
**QUEREMOS:Lograr** tener la documentación
**PARA QUE:** Para tener todo lo que hicimos en un solo lugar y que este ordenado

**Comment by jurgenru** [comment]
Historia de Usuario
<b>COMO:</b> Grupo
<b>QUEREMOS:</b> Lograr tener la documentación    
<b>PARA QUE:</b> Para tener todo lo que hicimos en un solo lugar y que este ordenado

**Comment by SergiusxD** [comment]
Fuimos creando la wiki estas dos semanas y al aal final lo acabamos con todos los requerimientos
