### ISSUE TITLE
Integración Continua

### ISSUE THREAD

**Issue by jurgenru** [Bits-nFingers/Bits-nFingers#32]
Historia de Usuario
**COMO:** Grupo
**QUEREMOS:** Tener una integración continua
**PARA QUE**: Para comprobar que todo el código esta bien

**Comment by SergiusxD** [comment]
Lo empece pero no entiendo

**Comment by SergiusxD** [comment]
ahora ya esta con Android

**Comment by SergiusxD** [comment]
Si esta funcionando para el Android Studio
