### ISSUE TITLE
Definir que base de datos usar

### ISSUE THREAD

**Issue by jurgenru** [Bits-nFingers/Bits-nFingers#4]
Historia de Usuario
**COMO:** Grupo
**QUEREMOS:** Definir que base de datos vamos a usar
**PARA QUE:** Para guardar los datos de manera correcta

**Comment by jurgenru** [comment]
Vamos a utilizar mongoDB y falta hacer el diagrama de la base de datos

**Comment by SergiusxD** [comment]
Creando diagrama para saber como va  hacer nuestra Base de daatos
https://docs.google.com/document/d/19N_KZ9NQWBA1syda8diAQzZCqlKJAh_38T9nTfpgs4k/edit?usp=sharing

**Comment by jurgenru** [comment]
Historia de Usuario
<b>COMO:</b> Grupo
<b>QUEREMOS:</b> Definir que base de datos vamos a usar  
<b>PARA QUE:</b> Para guardar los datos de manera correcta
