### ISSUE TITLE
Diseñar la interfaz de baja calidad

### ISSUE THREAD

**Issue by jurgenru** [Bits-nFingers/Bits-nFingers#5]
Historia de Usuario
**COMO:** Grupo
**QUEREMOS:** Diseñar la interfaz de baja calidad
**PARA QUE:** Para iniciar con la idea de como se vería para el usuario

**Comment by jurgenru** [comment]
Para los mock ups vamos a utilizar balsamiq

**Comment by AndreaAguilar26** [comment]
https://docs.google.com/document/d/1npEAPODTFyNdgL94WrbN151bXXHnYeP3mG1kMlQJgQw/edit?usp=sharing

**Comment by jurgenru** [comment]
Historia de Usuario
<b>COMO:</b> Grupo
<b>QUEREMOS:</b> Diseñar la interfaz de baja calidad  
<b>PARA QUE:</b> Para iniciar con la idea de como se vería para el usuario

**Comment by AndreaAguilar26** [comment]
![flujo de mockups](https://user-images.githubusercontent.com/57947101/70235367-33ed8400-1739-11ea-94a1-4095f35ed969.jpg)
![mockup](https://user-images.githubusercontent.com/57947101/69684302-9508be00-108e-11ea-9746-79efec110156.jpg)
![mockup3](https://user-images.githubusercontent.com/57947101/69684402-eadd6600-108e-11ea-8df7-412ea3eed519.jpg)
![mockup4](https://user-images.githubusercontent.com/57947101/70234614-6ac29a80-1737-11ea-97ed-0419c22db532.jpg)
![mockup0](https://user-images.githubusercontent.com/57947101/69765173-4b30de00-1149-11ea-8add-91663f5ba50e.jpg)
![mockup5](https://user-images.githubusercontent.com/57947101/69684436-0cd6e880-108f-11ea-8633-b01e4b8b732b.jpg)
![mockup6](https://user-images.githubusercontent.com/57947101/69684451-1bbd9b00-108f-11ea-8a58-d0d1340e7ca3.jpg)
![mockup7](https://user-images.githubusercontent.com/57947101/69684474-2710c680-108f-11ea-882c-3a20c936ba64.jpg)
![mockup8](https://user-images.githubusercontent.com/57947101/69684487-33951f00-108f-11ea-8528-fa3a2a6520d7.jpg)
![mockup9](https://user-images.githubusercontent.com/57947101/69684505-3f80e100-108f-11ea-88ba-ff994c2f21fc.jpg)
![mockup 10](https://user-images.githubusercontent.com/57947101/69684520-4c9dd000-108f-11ea-8e78-a37e09335585.jpg)
![mockup11](https://user-images.githubusercontent.com/57947101/69684536-59babf00-108f-11ea-8cbd-9674ecdfe911.jpg)
