### ISSUE TITLE
Definir los usuarios

### ISSUE THREAD

**Issue by jurgenru** [Bits-nFingers/Bits-nFingers#8]
Historia de Usuario
**COMO:** Grupo
**QUEREMOS:** Definir los usuarios
**PARA QUE:** Para poder desarrollar el sistema de manera precisa

**Comment by AndreaAguilar26** [comment]
* Responsable de almacén
* Personal 
* Técnico
* Responsable de Inventarios

**Comment by jurgenru** [comment]
Historia de Usuario
<b>COMO:</b> Grupo
<b>QUEREMOS:</b> Definir los usuarios  
<b>PARA QUE:</b> Para poder desarrollar el sistema de manera precisa
