### ISSUE TITLE
Definir si la aplicación es mobile o web

### ISSUE THREAD

**Issue by hrnn** [Bits-nFingers/Bits-nFingers#9]
Historia de Usuario
**COMO:** Grupo
**QUEREMOS:** Definir si la aplicacion es mobile o web
**PARA QUE:** Para poder implementarlo

**Comment by SergiusxD** [comment]
Falta aun discutir en que vamos hacer

**Comment by SergiusxD** [comment]
Al final decidimos ir por una aplicacion Movil, esto va implicar Android Studio

**Comment by jurgenru** [comment]
Historia de Usuario
<b>COMO:</b> Grupo
<b>QUEREMOS:</b> Definir si la aplicacion es mobile o web  
<b>PARA QUE:</b> Para poder implementarlo
